import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";
import Footer from "@/components/ui/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header />
      <main className="min-h-screen bg-gradient-to-r from-blue-100 to-purple-100 flex items-center justify-center">
      {children}
      </main>
      <Footer />
      </body>
    </html>
  );
}
