// app/layout.js
import './globals.css'; // Import global styles
import Header from '@/components/ui/header';
import Footer from '@/components/ui/footer';
import AppThemeProvider from './theme-provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppThemeProvider>
          <Header />
          <main className="min-h-[82vh] max-h-[84vh] bg-gradient-to-b from-[#00b7ff] to-[#f8f8ff] flex items-center justify-center">
            {children}
          </main>
          <Footer />
        </AppThemeProvider>
      </body>
    </html>
  );
}
